### ISSUE TITLE
Support custom Feeds for pypi detection. 

### ISSUE THREAD

**Issue by RushabhBhansali** [microsoft/component-detection#661] opened 2023-07-14 18:37 UTC
The current Pypi detector relys on package information on pypi.org feed. If customer is installing the python packages from custom feed from a different feed, this causes mismatch between detected and installed component versions. 

Request:
Add configuration to  support custom feed for pypi detector.

**Comment by RushabhBhansali** [comment] 2023-07-14 18:45
Customer request that led to this finding: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2081241

**Comment by melotic** [comment] 2023-07-14 19:31
duplicate of https://github.com/microsoft/component-detection/issues/415

**Closed by melotic** 2023-07-14 19:31 UTC
