### ISSUE TITLE
Silent error when parsing setup.py files

### ISSUE THREAD

**Issue by Omotola** [microsoft/component-detection#856] opened 2023-10-13 22:25 UTC
When packages are unable to be extracted from setup.py file the file is just skipped, and nothing is logged to show there was an issue while parsing the file.

Steps to reproducing the issue:

Running this customer reported[ setup.py file](https://github.com/Azure/azure-sdk-for-python/blob/48d1a765cc7802be5d47bdd3aed54133d162fc26/sdk/ml/azure-ai-ml/setup.py#L23) (or any bad setup.py file) in debug mode visual studio, if you place a breakpoint and step through the  `ExecuteCommandAsync' method in CommandLineInvocationService.cs ([L#76](https://github.com/microsoft/component-detection/blob/25e572f6b151b869798c24cf264b2ff20cf888ec/src/Microsoft.ComponentDetection.Common/CommandLineInvocationService.cs#L76)) you'll notice there is an Std Error (image below) before the method returns.

![Image](https://github.com/microsoft/component-detection/assets/8052624/f579b360-0d04-4736-afea-9e720e966c97)

the `ExecuteCommandAsync` method is called in `ParseSetupPyFileAsync` in PythonCommandService ([L#64](https://github.com/microsoft/component-detection/blob/25e572f6b151b869798c24cf264b2ff20cf888ec/src/Microsoft.ComponentDetection.Detectors/pip/PythonCommandService.cs#L64)), and that method checks if there is an ExitCode of 0 in which it returns the list of packages succesfully but if the exitCode is not 0, then it just returns an empty list as seen in the code snippet below without logging the StdError, which makes it difficult to know that an error occurred. 
```
        if (command.ExitCode != 0)
        {
            return new List<string>();
        }
```

AB#2113199

**Comment by melotic** [comment] 2023-10-13 22:37
Is this related to #108?

**Comment by Omotola** [comment] 2023-10-13 22:40
Actually, yeah. Duplicate of #242

**Comment by annaowens** [comment] 2023-11-13 22:05
Closing this issue as a duplicate of #242

**Closed by annaowens** 2023-11-13 22:05 UTC
Labels: duplicate, detector:pip
