### ISSUE TITLE
Pip: Exception when a component appears more than once

### ISSUE THREAD

**Issue by sonnb** [microsoft/component-detection#883] opened 2023-10-30 07:56 UTC
In my case, although in the requirement.text file numpy only appears one but it seems to be transitively linked from other components and when I run the scan, it throws those errors. I think it should nicely handle the case of duplication?

```c#
##[error]Component "0.1.1.post2209072238" : {ReleaseValue)} could not be added to the sorted list of pip components for spec="thop". Usually this happens with unexpected PyPi version formats (e.g. prerelease/dev versions).
System.ArgumentException: An item with the same key has already been added. Key: [0.1.1.post2209072238, System.Collections.Generic.List`1[Microsoft.ComponentDetection.Detectors.Pip.PythonProjectRelease]]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at Microsoft.ComponentDetection.Detectors.Pip.PyPiClient.GetReleasesAsync(PipDependencySpecification spec)
##[error]Error while parsing pip components in "/builds/xxx/yyy/requirements.txt"
System.ArgumentException: An item with the same key has already been added. Key: numpy
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.ComponentDetection.Detectors.Pip.PythonResolver.InvalidateAndReprocessAsync(PythonResolverState state, PipGraphNode node, PipDependencySpecification newSpec)
   at Microsoft.ComponentDetection.Detectors.Pip.PythonResolver.ProcessQueueAsync(ISingleFileComponentRecorder singleFileComponentRecorder, PythonResolverState state)
   at Microsoft.ComponentDetection.Detectors.Pip.PythonResolver.ResolveRootsAsync(ISingleFileComponentRecorder singleFileComponentRecorder, IList`1 initialPackages)
   at Microsoft.ComponentDetection.Detectors.Pip.PipComponentDetector.OnFileFoundAsync(ProcessRequest processRequest, IDictionary`2 detectorArgs)
``` 

AB#2119435

**Comment by cobya** [comment] 2023-11-29 20:09
Closing as a duplicate of #862

**Closed by cobya** 2023-11-29 20:09 UTC
